config/routes.rb
Rails.application.routes.draw do
  root "todo_lists#index"

  resources :todo_lists, only: [:index, :show, :edit, :update], shallow: true do
    resources :todos, only: [:create, :edit, :update, :destroy] do
      post :toggle, on: :member
      get :cancel_edit, on: :member
    end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :todo_list

  acts_as_list scope: [:todo_list_id, :completed]

  validates :name, :todo_list, presence: true

  scope :by_position, -> { order :position }
  scope :completed, -> { where completed: true }
  scope :uncompleted, -> { where completed: false }

  def toggle_completed!
    toggle!(:completed)
    move_to_top if completed?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todos, dependent: :destroy
  has_many :completed_todos, -> { where(completed: true).by_position }, class_name: "Todo"
  has_many :uncompleted_todos, -> { where(completed: false).by_position }, class_name: "Todo"

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update]

  def index
    redirect_to TodoList.first
  end

  def show
    @todo = Todo.new
  end

  def edit
  end

  def update
    unless @todo_list.update(todo_list_params)
      render "edit"
    end
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:name)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :cancel_edit, :update, :destroy, :toggle]

  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo = @todo_list.todos.build(todo_params)

    unless @todo.save
      head :ok
    end
  end

  def edit
  end

  def cancel_edit
    render "update"
  end

  def update
    unless @todo.update(todo_params)
      head :ok
    end
  end

  def destroy
    @todo.destroy
  end

  def toggle
    @todo.toggle_completed!
  end

  private

  def todo_params
    params.require(:todo).permit(:name)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>AjaxOnRailsMiniEdition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/todo_lists/_form.html.erb
<div id="modal" class="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title">Settings</h4>
      </div>
      <%= form_for todo_list, remote: true do |f| %>
        <div class="modal-body">
          <% if todo_list.errors.any? %>
            <div class="alert alert-danger form-errors">
              <ul class="list-unstyled">
                <% todo_list.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/todo_lists/edit.js.erb
// Remove previous modal
$("#modal, .modal-backdrop").remove();

// Add new modal before the </body> tag
$("body").append("<%= j render("form", todo_list: @todo_list) %>");

// Show the modal
$("#modal").modal();

app/views/todo_lists/show.html.erb
<div class="header clearfix">
  <%= link_to "Settings", edit_todo_list_path(@todo_list), remote: true, class: "pull-right" %>
</div>

<div class="todo-list">
  <h1 class="text-center"><%= @todo_list.name %></h1>

  <hr>

  <%= form_for [@todo_list, @todo], remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "Add a new todo...", autocomplete: :off %>
    </div>
  <% end %>

  <ul class="todos uncompleted list-unstyled">
    <%= render @todo_list.uncompleted_todos %>
  </ul>

  <ul class="todos completed list-unstyled">
    <%= render @todo_list.completed_todos %>
  </ul>
</div>

app/views/todo_lists/update.js.erb
// Update the heading and highlight it after the change, so user can easily see
// what changed
$("h1").html("<%= j @todo_list.name %>").effect("highlight", {}, 1500);

// Hide the settings form
$("#modal").modal("hide");

app/views/todos/_form.html.erb
<li id="<%= dom_id(todo) %>" class="todo">
  <%= form_for todo, remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", autocomplete: :off %>
    </div>
    <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
    <%= link_to "Cancel", cancel_edit_todo_path(todo), class: "btn btn-link btn-sm", remote: true %>
  <% end %>
</li>

app/views/todos/_todo.html.erb
<li id="<%= dom_id(todo) %>" class="todo">
  <%= check_box_tag dom_id(todo, :checkbox), todo.completed?, todo.completed?, data: { url: toggle_todo_path(todo), method: :post, remote: true } %>
  <span class="name">
    <%= todo.name %>
  </span>

  <% unless todo.completed? %>
    <span class="actions pull-right">
      <%= link_to "Edit", edit_todo_path(todo), remote: true %> /
      <%= link_to "Delete", todo_path(todo), method: :delete, data: { confirm: "Are you sure?" }, remote: true %>
    </span>
  <% end %>
</li>

app/views/todos/create.js.erb
// Add new todo to the end of the list
$("ul.todos.uncompleted").append("<%= j render(@todo) %>");

// Clear the input so user can add another todo
$("#todo_name").val("");

app/views/todos/destroy.js.erb
// Hide the deleted todo
$("#<%= dom_id(@todo) %>").fadeOut();

app/views/todos/edit.js.erb
// Replace todo with the edit form
$("#<%= dom_id(@todo) %>").replaceWith("<%= j render("form", todo: @todo) %>");

// Focus the input box so user can directly start to type
$('#<%= dom_id(@todo) %> input[type="text"]').focus();

app/views/todos/toggle.js.erb
// Remove the todo from its previous list
$("#<%= dom_id(@todo) %>").remove();

// Add todo its new list
<% if @todo.completed %>
  // If it is completed then put it in the beggining of the completed todos list
  $(".todos.completed").prepend("<%= j render(@todo) %>");
<% else %>
  // If it is not completed then put it in the end of the uncompleted todos list
  $(".todos.uncompleted").append("<%= j render(@todo) %>");
<% end %>

app/views/todos/update.js.erb
// Replace the todo with updated information
$("#<%= dom_id(@todo) %>").replaceWith("<%= j render(@todo) %>");